// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 04. 29. 18:18:13
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg4 from "./../../woonuxt_base/tailwind.config.ts";
const config = [
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","./components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/app.config.{js,ts,mjs}"]}},
{},
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/app.config.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/ acarpartsWoonuxt/woonuxt_base/app/app/spa-loading-template.html"]}},
cfg4
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;